grunt-config.js
gruntfile.js
lib/ChunklistManifestGenerator.js
lib/EntryDownloader.js
lib/FlavorDownloader.js
lib/MasterManifestGenerator.js
lib/NetworkClientFactory.js
lib/PersistenceFormat.js
lib/Worker.js
lib/grunt/config/component-tests-config.js
lib/grunt/tasks/component-test-task.js
lib/mocks/BackendClientMock.js
lib/utils/http-utils.js
package.json
tests/component/workerComponent-spec.js
tests/mocks/wowzaMock.js
tests/resources/liveSessionData/playlist.m3u8
tests/unit/BackendClientFactory-spec.js
tests/unit/ChunklistManifestGenerator-spec.js
tests/unit/EntryDownloader-spec.js
tests/unit/MasterManifestGenerator-spec.js
tests/unit/NetworkClientFactory-spec.js
tests/unit/PersistenceFormat-spec.js
tests/unit/flavor-downloader-spec.js
tests/unit/http-utils-spec.js
tests/unit/promise-m3u8-spec.js

* Fix chunk duration update bug

---

lib/ChunklistManifestGenerator.js
lib/SessionManager.js
tests/mocks/wowzaMock.js
tests/unit/ChunklistManifestGenerator-spec.js

Added some logging

---

common/config/config.json.template
lib/TwoPhasedChunklistManifestGenerator.js

Remove (wrong) port from default configuration template

---

dvr-ws/app.js

* Set env to production so stack traces aren't sent as part of the response

* Add caching header for ts files

---

lib/Adapters/WowzaAdapter.js
lib/Adapters/WowzaStreamInfo.js
lib/SessionManager.js
lib/Worker.js
lib/entry/FlavorDownloader.js
lib/entry/LiveEntry.js
lib/entry/StateManager.js
lib/manifest/PlaylistGenerator.js
lib/utils/promise-utils.js

PLAT-5389: Fix for fast disconnections and support to _publish entries

---

lib/utils/fs-utils.js

Revert "add qio.makeTree before rename"

---

lib/Worker.js

…atot call unregister on the live entry

0.12.0 fix quick start stop cancellation

---

lib/Adapters/WowzaAdapter.js

Revert "PLAT-5526: Fix Wowza adapter"

---

lib/playlistGenerator/GapPatcher.js
lib/playlistGenerator/MixFilterClip.js
lib/playlistGenerator/Playlist.js
lib/playlistGenerator/Sequence.js
tests/unit/PlaylistGenerator-spec.js

- fix PLAT-5843: display only clips which have totaled duration > 0 + add unit test
- Playlist.js add support for firstClipTime property (smooth streaming)
- Sequence.js:  sequence clips property get out of sync when popping a clip
- Playlist,js: reorder json for better viewing
- code cleanup
- Playlist.js: remove outdated logic which displays flavors with duration > 0

1.0-PLAT-5843

---

common/config/config.json.template
common/logger.js
serviceWrappers/linux/kLiveController

Logs are displayed in GMT time.

kLiveController service now installs node version if it doesn't exists.

---

lib/playlistGenerator/Playlist.js
lib/playlistGenerator/playlistGen-utils.js
tests/unit/PlaylistGenerator-spec.js

this time scenario goes like so:
- existing algorithm for clip duration calculation:
clip_start=min(start[n]) clip_end=min(end[n]), where n is flavor.
- if flavor k start[k] > clip_end packeger returns error 503.
solution:
for k in [0,n] if start[k]  >= clip_end return 0,
otherwise do as before.

-1.0-PLAT-5976

---

lib/playlistGenerator/ConcatSource.js
lib/playlistGenerator/MixFilterClip.js
lib/playlistGenerator/Playlist.js
lib/playlistGenerator/PlaylistGenerator.js

- added logs
- allowed for 0 length chunk due to gaps (split) inside mixclip range.
- mixfilter returns invalid range in case on of the concat sources has no data.

-1.0-PLAT-PLAT-5976-r

---

lib/playlistGenerator/ConcatSource.js
lib/playlistGenerator/MixFilterClip.js

- fix broken validateInput
- partial fix for *ts chunk mismatch* & *audio/video pts misalignment* alerts

1.0 staging

---

common/PersistenceFormat.js

fix for regression cleanup to work.

added missing method used for entry stream files cleanup

---

lib/playlistGenerator/Playlist.js
tests/unit/PlaylistGenerator-spec.js

- determining baseClipTime is deferred until all flavors are ready
- playlist is not written until first clip duration > 0

1.3-PLAT-6617

---

common/config/config.json.template
lib/BackendClient.js
lib/entry/FlavorDownloader.js
lib/entry/LiveEntry.js

dynamic downloader polling interval

1.6 PLAT 6859 support configurable latency

---

liveRecorder/Tasks/ConcatinationTask.py
liveRecorder/Tasks/UploadTask.py

correctly support extract of flavor id when recording has single flavor

---

liveRecorder/Tasks/TaskRunner.py

check if queue is full before fetching new recording concat tasks
Related to SUP-11185.

check if queue if full before getting new concat job

---

liveRecorder/Logger/LoggerDecorator.py
liveRecorder/Tasks/ConcatinationTask.py
liveRecorder/Tasks/TaskRunner.py
liveRecorder/Tasks/ThreadWorkers.py

now checking if queue is full every ready file (job).

merge LiveRecoder update (plat-7473)

---

liveRecorder/Tasks/ConcatinationTask.py

corrected handling sub process end status.

corrected handling exit code and returned values from sub process

---

deployment/get_bins.sh
deployment/upgradeLive.sh

merge updated upgradelive and get_bins scripts

merge to 1.14, QA upgrade scripts update

---

deployment/get_bins
deployment/upgradeLive

1.14 qa scripts name refactory

merge qa scripts update + rename

---

deployment/upgradeLive

Enhanced script to enable downgrade and upgradeLive script update

merge QA upgrade scripts update to 1.15

---

liveRecorder/Config/config.template.ini
liveRecorder/Config/configMapping.ini.template

+updated liveRecorder configuration template:
partner_id = @KALTURA_PARTNER_ID@
mode = @VOD_UPLOAD_MODE@
cron_job_log_file_name = "@LOGS_BASE_PATH@/recording_cron.log"
log_file_name = "@LOGS_BASE_PATH@/liveRecorder.log"
recover_log_file_name = "@LOGS_BASE_PATH@/recorder.log"
api_service_url = @KALTURA_SERVICE_URL@

merge to 1.16 on-prem templates perp

---

liveRecorder/Config/config.template.ini
liveRecorder/Config/configMapping.ini.template

+updated liveRecorder configuration template:
partner_id = @KALTURA_PARTNER_ID@
mode = @VOD_UPLOAD_MODE@
cron_job_log_file_name = "@LOGS_BASE_PATH@/recording_cron.log"
log_file_name = "@LOGS_BASE_PATH@/liveRecorder.log"
recover_log_file_name = "@LOGS_BASE_PATH@/recorder.log"
api_service_url = @KALTURA_SERVICE_URL@

merge to 1.16 onPrem templates prep

---

liveRecorder/Tasks/UploadTask.py

fix upload VOD of recording job created by zombie recover cron

merge to 1.16 fix VOD upload for recording zombie job

---

lib/Diagnostics/Diagnostics.js
lib/Diagnostics/DiagnosticsAlerts.js

1) Make sure each alert is only reported once.

Fix alerts beacon handling to send each alert once

---

lib/Diagnostics/DiagnosticsAlerts.js
lib/Diagnostics/DiagnosticsAnalyzer.js

1) Make sure each alert is only reported once.

Fix alerts beacon handling:

---

liveRecorder/serviceWrappers/linux/liveRecorder

fix running python command from liveRecorder script

merge to 1.17 fix in liveRecorder script

---

lib/recording/RecordingEntrySession.js
lib/recording/RecordingManager.js

+ delete RecordingEntrySession from getRecordingEntry in case of split
recording due to 24/7 or flavors mismatch

releease mp4 files lock

---

lib/recording/RecordingEntrySession.js
lib/recording/RecordingManager.js

If recordingEntryId didn’t change and split done the recording in backup will be disabled

disable recording in backup in edge use case

---

liveRecorder/Tasks/TaskRunner.py

now handles error such as: recorded content dir not found

merge to 1.19 fix in getSorterFileList

---

lib/recording/RecordingEntrySession.js
lib/recording/RecordingManager.js

merge to 1.19 fix infinite split in LIVE_BACKUP

---

lib/entry/StateManager.js
liveRecorder/Tasks/TaskRunner.py

The change fixes flow that jobs stuck in ConcatenationTask and
UploadTask processing dirs.

merge plat-8051 fix

---

lib/recording/RecordingEntrySession.js
lib/recording/RecordingManager.js

create recording job either if the session duration is greater than
threshold or last session didn’t finish gracefully

merge plat-8162 - fine tune recording job create conditions

---

build_scripts/build_binaries.sh

added script to build binaries (ffmpeg, formatConverter and ts_to_mp4_convertor)

merge new script build_binaries.sh

---

packager/config/nginx.conf.live.conf.template

https://github.com/kaltura/nginx-vod-module/blob/master/CHANGELOG.md#20170813---hlsfmp4-support

Update for nginx-vod-module 1.19

---

lib/recording/RestoreRecordingFromBackup.js
liveRecorder/Config/config.ini

added new script to restore recording from backup DC

merge script to restore recording from backup

---

liveRecorder/serviceWrappers/defaults/liveRecorder
liveRecorder/serviceWrappers/linux/liveRecorder

merge liveRecorder script update to 1.23
